#!/bin/bash

vol=$(pactl list sinks | grep "Volume" | grep -hEo "[[:digit:]]{1,3}%" | head -1 | grep -o "[^%]" | tr -d '\n')
mute=$(pactl list sinks | grep "Mute" | grep -Eo "(yes|no)")


get_icon() {
    if [ "$1" == "a" ]; then
	if [ "$vol" -gt "66" ]; then
	    echo "\\ue903"
	elif [ "$vol" -gt "33" ]; then
	    echo "\\ue906"
	elif [ "$vol" -gt "0" ]; then
	    echo "\\ue904"
	elif [ "$vol" -eq "0" ]; then
	    echo "\\ue90e"
    fi
    elif [ "$1" == "b" ]; then
	if [ "$vol" -gt "66" ]; then
	    echo "\\u00"
	elif [ "$vol" -gt "33" ]; then
	    echo "\\ue907"
	elif [ "$vol" -gt "0" ]; then
	    echo "\\ue905"
	elif [ "$vol" -eq "0" ]; then
	    echo "\\ue91b"
	fi
    fi
}

if [ "$1" == "--icon-a" ]; then
    get_icon a
elif [ "$1" == "--icon-b" ]; then
    get_icon b
fi
