#!/bin/bash

connect=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g' | tr '-' ' ')
power=$(nmcli -f in-use,signal dev wifi | grep '*' | awk '{print $2}')
state=""


get_type() {
    if [[ -n $(echo "$connect" | grep 'Wired') ]]; then
	state="Wired Connection"
    elif [ "$connect" == "lo" ]; then
	state="Disconnected"
    else
	state="Wi-Fi Connection to: ($connect)"
    fi

    echo "$state"
}

get_icon() {
    if [ "$1" == "a" ]; then
	if [[ -n $(echo "$connect" | grep 'Wired') ]]; then
	    echo "\\ue900"
	elif [ "$power" == "" ]; then
	    echo "\\ue901"
	elif [ "$power" -gt "66" ]; then
            echo "\\ue908"
	elif [ "$power" -gt "33" ]; then
       	    echo "\\ue90b"
	elif [ "$power" -ge "0" ]; then
       	    echo "\\ue909"
	fi
    elif [ "$1" == "b" ]; then
	if [[ -n $(echo "$connect" | grep 'Wired') ]]; then
	    echo "\\u00"
	elif [ "$power" == "" ]; then
	    echo "\\u00"
	elif [ "$power" -gt "66" ]; then
            echo "\\u00"
	elif [ "$power" -gt "33" ]; then
       	    echo "\\ue90c"
	elif [ "$power" -ge "0" ]; then
       	    echo "\\ue90a"
	fi
    fi
}



if [ "$1" == "--type" ]; then
    get_type
elif [ "$1" == "--icon-a" ]; then
    get_icon a
elif [ "$1" == "--icon-b" ]; then
    get_icon b
fi
