#!/bin/bash

config="~/.config/eww/eww.conf"

screen() {
    if [[ `awk '/auto-res/ {gsub("= | =|= |=", " "); print $2}' ~/.config/eww/eww.conf` == "false" ]]; then
	if [[ "$1" == "width" ]]; then
	    echo `awk '/screen-width/ {gsub("= | =|= |=", " "); print $2}' ~/.config/eww/eww.conf`
	elif [[ "$1" == "height" ]]; then
	    echo `awk '/screen-height/ {gsub("= | =|= |=", " "); print $2}' ~/.config/eww/eww.conf`
	fi
    elif [[ `awk '/auto-res/ {gsub("= | =|= |=", " "); print $2}' ~/.config/eww/eww.conf` == "true" ]]; then
	if [[ "$1" == "width" ]]; then
	    echo `hyprctl monitors -j | grep "width" | grep -hEo "[[:digit:]]*"`
	elif [[ "$1" == "height" ]]; then
	    echo `hyprctl monitors -j | grep "height" | grep -hEo "[[:digit:]]*"`
	fi
    fi

}

if [[ "$1" == "--width" ]]; then
    screen "width"
elif [[ "$1" == "--height" ]]; then
    screen "height"
fi

